# Generated by Django 3.1.1 on 2020-10-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorterdb', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagesTesting',
        ),
        migrations.AlterField(
            model_name='imagestraining',
            name='img',
            field=models.FileField(upload_to='images-training'),
        ),
    ]
